### PR TITLE
SDK-324: openmrs-sdk:run" not working with SDK version 5.4.0

### PR DESCRIPTION
**Pull request by wikumChamith**
## Description of what I changed

This resolves the `java.lang.NoSuchMethodError: com.google.common.base.Platform.stringIsNullOrEmpty` error when starting docker containers.
## Issue I worked on

see https://openmrs.atlassian.net/browse/SDK-324

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean install` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute the above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks for the prompt response @wikumChamith !  Generally defer to @dkayiwa  on this... seems to be some sort of dependency issue, I take it, @wikumChamith ? Can you explain what is going on here?

**Comment by wikumChamith** [comment]
@mogoodrich  We added guava [here](https://github.com/openmrs/openmrs-sdk/commit/2623cd97af4e912744a93b01e238c9a2a80d8077#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8). Guava contains `google-collections` which is not supported on` plexus-container-default`. So I made  `google-collections` as an exclusion for plexus-container-default dependency.

**Comment by mogoodrich** [comment]
thanks @wikumChamith !

**Comment by gracepotma** [comment]
Bravo @wikumChamith for this rapid turnaround!!
